export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  BENEFICIARIES: '/beneficiarios',
  BENEFICIARY_NEW: '/beneficiarios/nuevo',
  BENEFICIARY_DETAIL: (id: number | string) => `/beneficiarios/${id}`,
  BENEFICIARY_EDIT: (id: number | string) => `/beneficiarios/${id}/editar`,
  BENEFICIARY_HEALTH: (id: number | string) => `/beneficiarios/${id}/salud`,
  ATTENDANCE: '/asistencia',
  ATTENDANCE_CHECKIN: '/asistencia/check-in',
  ATTENDANCE_HISTORY: '/asistencia/historial',
  KITCHEN: '/cocina',
  KITCHEN_DIETARY: '/cocina/dietario',
  KITCHEN_OPERATIONAL: '/cocina/operacional',
  INGREDIENTS: '/ingredientes',
  INGREDIENT_NEW: '/ingredientes/nuevo',
  INGREDIENT_EDIT: (id: number | string) => `/ingredientes/${id}/editar`,
  MEALS: '/comidas',
  MEAL_NEW: '/comidas/nueva',
  MEAL_DETAIL: (id: number | string) => `/comidas/${id}`,
  MEAL_EDIT: (id: number | string) => `/comidas/${id}/editar`,
  PREDICTIONS: '/predicciones',
  PROFILE: '/mi-perfil',
  USERS: '/usuarios',
  USER_NEW: '/usuarios/nuevo',
  USER_EDIT: (id: number | string) => `/usuarios/${id}/editar`,
} as const;
